---
title: "Preprocessing script"
author: "Ashish"
date: ""
output: rmdformats::readthedown
---

# Initialization
```{r, message=FALSE}
rm(list=ls())
library(here)
library(tidyverse)
library(tidylog)
theme_set(theme_bw())
```

# Preprocessing 
## Functions 
```{r, message=F, warning=F}
codebook_renamer <- function(df, codebook, 
                             old_col_name="old_col_name",
                             new_col_name="new_col_name"){
  codebook <- codebook %>%
    dplyr::filter(.data[[old_col_name]] %in% names(df))
  df %>% 
  rename_at(vars(codebook[[old_col_name]]), ~codebook[[new_col_name]])
}

codebook_recoder <- function(df,
                             codebook,
                             var_col_name="var_regex",
                             old_value_col="old_value",
                             new_value_col="new_value",
                             to_numeric=TRUE){
  require(dplyr)
  var_regexes <- unique(codebook[[var_col_name]])
  recode_column <- function(column, level_key){dplyr::recode(tolower(column), !!!level_key)}
  for(var in var_regexes){
    level_key <- codebook %>% 
      # --  remove line breaks -- #
      dplyr::mutate_at(vars(one_of(old_value_col)), ~str_replace_all(., "\\\r|\\\n", "")) %>%
      dplyr::filter(.data[[var_col_name]]==!!var) %>% 
      dplyr::mutate("{old_value_col}" := tolower(.data[[old_value_col]])) %>% 
      dplyr::select(one_of(old_value_col, new_value_col)) %>%
      deframe
    df <- df %>% 
      dplyr::mutate_at(vars(matches(paste0("^", var))), ~str_replace_all(., "\\\r|\\\n", "")) %>% 
      dplyr::mutate_at(vars(matches(paste0("^", var))), ~recode_column(., level_key))
    if(to_numeric){df <- df %>% dplyr::mutate_at(vars(matches(paste0("^", var))), as.numeric)}
  }
  return(df)
}
tally_scale <- function(df, 
                        scale_regex, 
                        new_col_name=NULL, 
                        pid_col="pid", 
                        join_function=dplyr::full_join, 
                        na.rm=F, 
                        tally_function=sum){
  # if user did not supply a new column name, use the scale_regex
  if(is.null(new_col_name)) new_col_name <- scale_regex 
  # check is there are duplicate participant IDs
  if(any(duplicated(df[[pid_col]]))){stop("Duplicate IDs found")}
  # append caret to start of regex
  scale_regex <- paste0("^", scale_regex) 
  # identify columns to tally
  cols_to_tally <- names(df)[str_detect(names(df), scale_regex)] 
  print(paste0("[",new_col_name, "] tallying columns:"))
  print(cols_to_tally)
  df_tally <- df %>% 
    dplyr::select(one_of(pid_col), one_of(cols_to_tally)) %>% # select columns to aggregate
    tidyr::pivot_longer(-one_of(pid_col)) %>% # convert to long format 
    dplyr::group_by_at(pid_col) %>% # group by participant
    dplyr::mutate(value = as.numeric(value)) %>% # change values to numeric
    dplyr::summarize(!!new_col_name := tally_function(value, na.rm=na.rm)) # aggregate according to tally_function
  if(!is.null(join_function)){
    df_tally <- df %>%
      join_function(df_tally) # join aggregated scores with original dataframe using join_function
  }
  return(df_tally)
}

```

## Read data
```{r, message=F}
codebook_filepath <- here("doc/Winter_2020_Survey_EWB_S2B_National_April_26_2021_11_30_codebook.xlsx")
codebook_vars <- readxl::read_excel(codebook_filepath, sheet="variables")
codebook_values <- readxl::read_excel(codebook_filepath, sheet="values") %>% 
  mutate(old_value = str_replace_all(old_value, "\r|\n", ""))

df_file <- readxl::read_excel(here("data/raw/2021-06-03/national_study_2b_raw.xlsx")) %>% 
  filter_all(any_vars(!is.na(.)))
df_raw <- df_file %>% 
  slice(-1:-2) %>%
  # -- rename columns -- #
  codebook_renamer(codebook=codebook_vars)


```

## Constants
```{r, message=F}
columns_to_numeric <- c("nature_time", "age", "perceived_exertion")
```

## Functions
```{r}
get_race <- function(race_column){
  # Function to turn race column into several columns with binary values
  tibble(
    white = str_detect(race_column, "White"),
    black = str_detect(race_column, "Black"),
    amindian = str_detect(race_column, "American Indian"),
    eastasian = str_detect(race_column, "East Asian"),
    filipino = str_detect(race_column, "Filipin"),
    seasian = str_detect(race_column, "Southeast Asian"),
    otherasian = str_detect(race_column, "Other Asian"),
    pacisland = str_detect(race_column, "Pacific"),
    chicano = str_detect(race_column, "Chican"),
    puertorican = str_detect(race_column, "Puerto"),
    centralamerican = str_detect(race_column, "Central American"),
    southamerican = str_detect(race_column, "South American"),
    otherlatin = str_detect(race_column, "Other Hispanic"),
    other = str_detect(race_column, "Other(?! Hispanic)(?! Asian)"),
    prefernot = str_detect(race_column, "Prefer not")
  ) %>% 
    rename_all(~paste0("race_", .)) %>% 
    mutate_all(as.integer)
}
```


## Process data

```{r, message=F}
df_recoded <- df_raw %>%
	# -- recode variables -- #
	codebook_recoder(codebook=codebook_values) %>% 
  mutate(perceived_exertion = str_extract(perceived_exertion, "^[0-9]*"))
```


```{r, message=F}
df_proc <- df_recoded %>%
  
  # -- remove failed attention checks -- #
  filter(ac_1 == 1 & ac_2 == 1 & ac_3 == 1 & ac_4 == 1) %>% 
  
  # -- create pids -- #
  mutate(pid = seq(from = 1000, length.out = n())) %>%

  # -- revalue invalid age, e.g. age = 2000 becomes age = 21 -- #
  mutate(age = as.numeric(age))%>%
  mutate(age = ifelse(age > 1000, 2021-age, age)) %>%
  
  # -- assign NA to people who don't report income -- #
  mutate(income = ifelse(income == "Prefer not to say", NA, income)) %>%

  # -- create log transformed nature time -- #
  mutate(nature_time = as.numeric(nature_time)) %>%
  mutate(nature_time_log = ifelse(nature_time == 0, nature_time, log(nature_time))) %>%
  
  # -- tally scales -- # 
  tally_scale("paq.*[0-9]{1,2}$", "paq") %>% 
  tally_scale("paq_.*_dif_[0-9]{1,2}$", "paq_dif") %>% 
  tally_scale("paq_.*_ddf_[0-9]{1,2}$", "paq_ddf") %>% 
  tally_scale("paq_.*_eot_[0-9]{1,2}$", "paq_eot") %>% 
  tally_scale("paq_pos_.*_[0-9]{1,2}$", "paq_pos") %>% 
  tally_scale("paq_neg_.*_[0-9]{1,2}$", "paq_neg") %>% 
  tally_scale("paq_neg_dif_[0-9]{1,2}$", "paq_neg_dif") %>% 
  tally_scale("paq_neg_ddf_[0-9]{1,2}$", "paq_neg_ddf") %>% 
  tally_scale("paq_pos_dif_[0-9]{1,2}$", "paq_pos_dif") %>% 
  tally_scale("paq_pos_ddf_[0-9]{1,2}$", "paq_pos_ddf") %>% 
  
  tally_scale("pmerq_(recons|repurp)_.*_[0-9]{1,2}$", "pmerq_reappraise") %>% 
  tally_scale("pmerq_attdep_.*_[0-9]{1,2}$", "pmerq_attdep") %>% 
  
  tally_scale("sitselect_(approach|avoid)_[1-6]$", "sitselect") %>% 
  tally_scale("sitselect_approach_[1-6]$", "sitselect_approach") %>% 
  tally_scale("sitselect_avoid_[1-6]$", "sitselect_avoid") %>% 
  tally_scale("pmerq_sitsel_dis_[0-9]{1,2}$", "pmerq_sitsel_dis") %>%
  tally_scale("pmerq_sitsel_eng_[0-9]{1,2}$", "pmerq_sitsel_eng") %>%
  tally_scale("pmerq_sitmod_eng_[0-9]{1,2}$", "pmerq_sitmod_eng") %>%
  tally_scale("pmerq_sitmod_dis_[0-9]{1,2}$", "pmerq_sitmod_dis") %>%
  tally_scale("pmerq_attdep_eng_[0-9]{1,2}$", "pmerq_attdep_eng") %>%
  tally_scale("pmerq_attdep_dis_[0-9]{1,2}$", "pmerq_attdep_dis") %>%
  tally_scale("pmerq_recons_eng_[0-9]{1,2}$", "pmerq_recons_eng") %>%
  tally_scale("pmerq_recons_dis_[0-9]{1,2}$", "pmerq_recons_dis") %>%
  tally_scale("pmerq_recons_(dis|eng)_[0-9]{1,2}$", "pmerq_recons") %>%
  tally_scale("pmerq_repurp_eng_[0-9]{1,2}$", "pmerq_repurp_eng") %>%
  tally_scale("pmerq_repurp_dis_[0-9]{1,2}$", "pmerq_repurp_dis") %>%
  tally_scale("pmerq_repurp_(eng|dis)_[0-9]{1,2}$", "pmerq_repurp") %>%
  tally_scale("pmerq_respmod_dis_[0-9]{1,2}$", "pmerq_respmod_dis") %>%
  tally_scale("pmerq_respmod_eng_[0-9]{1,2}$", "pmerq_respmod_eng") %>%

  tally_scale("fm_[0-9]{1,2}$", "fm") %>%
  tally_scale("swl_[1-5]$", "swl") %>%
  tally_scale("pss_", "pss") %>%
  tally_scale("fcv_[1-7]$", "fcv") %>%
  tally_scale("sds_", "sds") %>%

  tally_scale("panas_pos_[0-9]{1,2}$", "panas_pos") %>%
  tally_scale("panas_neg_[0-9]{1,2}$", "panas_neg") %>%

  tally_scale("rrs_brood_[0-9]$", "rrs_brood") %>%
  
  tally_scale("tas_", "tas") %>%
  tally_scale("tas_dif_[0-9]{1,2}$", "tas_dif") %>%
  tally_scale("tas_ddf_[0-9]{1,2}$", "tas_ddf") %>%
  tally_scale("tas_eot_[0-9]{1,2}$", "tas_eot") %>%
  
  tally_scale("ace_[0-9]$", "ace") %>% 
  
  # -- data types -- #
  mutate_at(vars(one_of(columns_to_numeric)), as.numeric) %>% 
  # -- re-order factors -- #
  mutate(edu = factor(edu, levels = c( 
    "Less than high school degree",
    "High school graduate (high school diploma or equivalent including GED)",
    "Some college but no degree",
    "Associate degree in college (2-year)",
    "Bachelor's degree in college (4-year)",
    "Master's degree",
    "Professional degree (JD, MD)",
    "Doctoral degree"
  ))) %>% 
  
  mutate(income = factor(income, levels = c(
    "Less than $10,000",
    "$10,000 to $19,999",
    "$20,000 to $29,999",
    "$30,000 to $39,999",
    "$40,000 to $49,999",
    "$50,000 to $59,999",
    "$60,000 to $69,999",
    "$70,000 to $79,999",
    "$80,000 to $89,999",
    "$90,000 to $99,999",
    "$100,000 to $149,999",
    "$150,000 to $199,999",
    "$200,000 to $249,999",
    "$250,000 to $299,999",
    "$300,000 or more"
  ))) %>%
  
  mutate(nature_freq_factor = as.factor(as.character(nature_freq))) %>% 
  mutate(nature_freq_factor = forcats::fct_recode(nature_freq_factor,
                                                  "Never" = "1",
                                                  "Once a year" = "2",
                                                  "Once every three months" = "3",
                                                  "Once a month" = "4",
                                                  "2-3 times a month" = "5",
                                                  "Once a week" = "6",
                                                  "2-3 days a week" = "7",
                                                  "3-5 days a week" = "8",
                                                  "6-7 days a week" = "9")
         ) %>%
  
  # -- discretizing continuous variables for visualizations -- #
  mutate(high_ace = case_when(
    ace <= 4 ~ 0, 
    ace > 4 ~ 1)) %>% 
  mutate(high_macarthur_us_rung = case_when(
    macarthur_us_rung <= median(macarthur_us_rung) ~ 0,
    macarthur_us_rung > median(macarthur_us_rung) ~ 1)) %>% 
  mutate(high_macarthur_comm_rung = case_when(
    macarthur_comm_rung <= median(macarthur_comm_rung) ~ 0,
    macarthur_comm_rung > median(macarthur_comm_rung) ~ 1)) %>% 
  cbind(get_race(.$race))
```



```{r, echo=FALSE}
# ------ End Preprocessing ------ #
# ----- Run all chunks above -----#
```

# 
```{r}
filepath_output <- "data/proc/national_study_2b_proc.csv"
df_proc %>% 
  write_csv(here(filepath_output))
```


# Session Info
```{r}
sessionInfo()
```

