---
title: "UW pool ER National Qualtrics Study"
author: "Ashish"
date: "2021-06-01"
output: rmdformats::readthedown
params:
  inputfile: ""
  outputfile: ""
  codebook_file: ""
---

# Initialization
```{r, message=FALSE}
rm(list=ls())
library(lavaan)
library(lmerTest)
library(here)
library(glue)
library(tidyverse)
library(tidylog)
require(rmdformats)
theme_set(theme_bw())
```

# Preprocessing 
## Functions 
```{r, message=F, warning=F}
codebook_renamer <- function(df, codebook, old_col_name="old_col_name", new_col_name="new_col_name"){
  codebook <- codebook %>%
    dplyr::filter(.data[[old_col_name]] %in% names(df))
  df %>% 
  rename_at(vars(codebook[[old_col_name]]), ~codebook[[new_col_name]])
}

# Note: new recoder function. not working with this codebook. can figure out later
# codebook_recoder <- function(df,
#                              codebook,
#                              var_col_name="var_regex",
#                              old_value_col="old_value",
#                              new_value_col="new_value",
#                              to_numeric=TRUE){
#   require(dplyr)
#   var_regexes <- unique(codebook[[var_col_name]])
#   recode_column <- function(column, level_key){dplyr::recode(tolower(column), !!!level_key)}
#   for(var in var_regexes){
#     level_key <- codebook %>% 
#       # --  remove line breaks -- #
#       dplyr::mutate_at(vars(one_of(old_value_col)), ~str_replace_all(., "\\\r|\\\n", "")) %>%
#       dplyr::filter(.data[[var_col_name]]==!!var) %>% 
#       dplyr::mutate("{old_value_col}" := tolower(.data[[old_value_col]])) %>% 
#       dplyr::select(one_of(old_value_col, new_value_col)) %>%
#       deframe
#     df <- df %>% 
#       dplyr::mutate_at(vars(matches(paste0("^", var))), ~str_replace_all(., "\\\r|\\\n", "")) %>% 
#       dplyr::mutate_at(vars(matches(paste0("^", var))), ~recode_column(., level_key))
#     if(to_numeric){df <- df %>% dplyr::mutate_at(vars(matches(paste0("^", var))), as.numeric)}
#   }
#   return(df)
# }
recoder <- function(column, var_regex, var_col_name, codebook=codebook_values){
  codebook <- codebook %>%
    dplyr::filter(!is.na(old_value) | !is.na(new_value)) %>% 
    dplyr::mutate_at(vars(old_value, new_value), ~replace_na(., "<na_value>"))
  column <- column %>% 
    replace_na(., "<na_value>")
	level_key <- codebook %>%
	  dplyr::filter(.data[[var_col_name]]==!!var_regex) %>% 
	  dplyr::mutate(old_value = tolower(old_value)) %>% 
		dplyr::select(old_value, new_value) %>%
		deframe
	level_key <- c(level_key, "<na_value>"=NA)
	recoded_column <- recode(tolower(column), !!!level_key)
	 return(recoded_column)
}
codebook_recoder <- function(df, codebook, var_col_name="var_regex"){
  var_regexes <- unique(codebook[[var_col_name]])
  for(var in var_regexes){
    df <- df %>% 
      dplyr::mutate_at(vars(matches(paste0("^", var))), ~str_replace_all(., "\\\r|\\\n", "")) %>% 
      dplyr::mutate_at(vars(matches(paste0("^", var))), ~recoder(., var_regex=var, var_col_name=var_col_name)) %>% 
      dplyr::mutate_at(vars(matches(paste0("^", var))), as.numeric)
  }
  return(df)
}
tally_scale <- function(df, 
                        scale_regex, 
                        new_col_name=NULL, 
                        pid_col="pid", 
                        join_function=dplyr::full_join, 
                        na.rm=F, 
                        tally_function=sum){
  # if user did not supply a new column name, use the scale_regex
  if(is.null(new_col_name)) new_col_name <- scale_regex 
  # check is there are duplicate participant IDs
  if(any(duplicated(df[[pid_col]]))){stop("Duplicate IDs found")}
  # append caret to start of regex
  scale_regex <- paste0("^", scale_regex) 
  # identify columns to tally
  cols_to_tally <- names(df)[str_detect(names(df), scale_regex)] 
  print(paste0("[",new_col_name, "] tallying columns:"))
  print(cols_to_tally)
  df_tally <- df %>% 
    dplyr::select(one_of(pid_col), one_of(cols_to_tally)) %>% # select columns to aggregate
    tidyr::pivot_longer(-one_of(pid_col)) %>% # convert to long format 
    dplyr::group_by_at(pid_col) %>% # group by participant
    dplyr::mutate(value = as.numeric(value)) %>% # change values to numeric
    dplyr::summarize(!!new_col_name := tally_function(value, na.rm=na.rm)) # aggregate according to tally_function
  if(!is.null(join_function)){
    df_tally <- df %>%
      join_function(df_tally) # join aggregated scores with original dataframe using join_function
  }
  return(df_tally)
}

```

## Read data
```{r, message=F}
codebook_filepath <- params$codebook_file
# codebook_filepath <- "doc/Codebook_Study_2a_Psych_Pool_Winter2021_EWB_Shift_Persist.xlsx"
codebook_vars <- readxl::read_excel(here(codebook_filepath), sheet="variables")
codebook_values <- readxl::read_excel(here(codebook_filepath), sheet="values") %>% 
  mutate(old_value = str_replace_all(old_value, "\r", ""))

# data_filepath <- "data/raw/Study_2A_UW_Psych_Pool_EWB_GB.xlsx"
data_filepath <- params$inputfile
df_file <- readxl::read_excel(here(data_filepath)) %>% 
  filter_all(any_vars(!is.na(.)))

df_raw <- df_file %>% 
  slice(-1:-2) %>% 
  # -- rename columns -- #
  codebook_renamer(codebook=codebook_vars)


```

## Constants
```{r, message=F}
columns_to_numeric <- c("nature_time", "age", "perceived_exertion")
```

## Functions
```{r}
get_race <- function(race_column){
  # Function to turn race column into dataframe with race columns with binary values
  tibble(
    white = str_detect(race_column, "White"),
    black = str_detect(race_column, "Black"),
    amindian = str_detect(race_column, "American Indian"),
    eastasian = str_detect(race_column, "East Asian"),
    filipino = str_detect(race_column, "Filipin"),
    seasian = str_detect(race_column, "Southeast Asian"),
    otherasian = str_detect(race_column, "Other Asian"),
    pacisland = str_detect(race_column, "Pacific"),
    chicano = str_detect(race_column, "Chican"),
    puertorican = str_detect(race_column, "Puerto"),
    centralamerican = str_detect(race_column, "Central American"),
    southamerican = str_detect(race_column, "South American"),
    otherlatin = str_detect(race_column, "Other Hispanic"),
    other = str_detect(race_column, "Other(?! Hispanic)(?! Asian)"),
    prefernot = str_detect(race_column, "Prefer not")
  ) %>% 
    rename_all(~paste0("race_", .)) %>% 
    mutate_all(as.integer)
}

```


## Process data

```{r, message=F}
df_recoded <- df_raw %>%
	# -- recode variables -- #
  codebook_recoder(codebook=codebook_values)
```


```{r, message=F}
df_proc <- df_recoded %>%
  
  # -- remove failed attention checks -- #
  filter(ac_1 == 1 & ac_2 == 1 & ac_3 == 1) %>% 
  
  # -- create pids -- #
  mutate(pid = seq(from = 1000, length.out = n())) %>%
  select(pid, everything()) %>% 

  # -- revalue invalid age, e.g. age = 2000 becomes age = 21 -- #
  mutate(age = as.numeric(age)) %>%
  mutate(age = ifelse(age > 1000, 2021-age, age)) %>%
  
  # -- assign NA to people who don't report income -- #
  mutate(income = ifelse(income == "Prefer not to answer", NA, income)) %>%

  # -- create log transformed nature time -- #
  mutate(nature_time = as.numeric(nature_time)) %>%
  mutate(nature_time_log = ifelse(nature_time == 0, nature_time, log(nature_time))) %>%
  
  # -- tally scales -- # 
  tally_scale("erq_fr_reap_[0-9]$", "erq_fr_reap") %>% 
  tally_scale("erq_fr_supp_[0-9]$", "erq_fr_supp") %>% 
  tally_scale("erq_fr_dist_[0-9]$", "erq_fr_dist") %>% 
  tally_scale("erq_se_reap_[0-9]$", "erq_se_reap") %>% 
  tally_scale("erq_se_supp_[0-9]$", "erq_se_supp") %>% 
  tally_scale("erq_se_dist_[0-9]$", "erq_se_dist") %>% 
  
  tally_scale("paq.*[0-9]{1,2}$", "paq") %>% 
  tally_scale("paq_.*_dif_[0-9]{1,2}$", "paq_dif") %>% 
  tally_scale("paq_.*_ddf_[0-9]{1,2}$", "paq_ddf") %>% 
  tally_scale("paq_.*_eot_[0-9]{1,2}$", "paq_eot") %>% 
  tally_scale("paq_pos_.*_[0-9]{1,2}$", "paq_pos") %>% 
  tally_scale("paq_neg_.*_[0-9]{1,2}$", "paq_neg") %>% 
  tally_scale("paq_neg_dif_[0-9]{1,2}$", "paq_neg_dif") %>% 
  tally_scale("paq_neg_ddf_[0-9]{1,2}$", "paq_neg_ddf") %>% 
  tally_scale("paq_pos_dif_[0-9]{1,2}$", "paq_pos_dif") %>% 
  tally_scale("paq_pos_ddf_[0-9]{1,2}$", "paq_pos_ddf") %>% 
  
  
  tally_scale("sitselect_(approach|avoid)_[1-6]$", "sitselect") %>% 
  tally_scale("sitselect_approach_[1-6]$", "sitselect_approach") %>% 
  tally_scale("sitselect_avoid_[1-6]$", "sitselect_avoid") %>% 

  tally_scale("fm_[0-9]{1,2}$", "fm") %>%
  tally_scale("swl_[1-5]$", "swl") %>%
  tally_scale("ewb_[1-5]$", "ewb") %>%
  tally_scale("pss_", "pss") %>%
  tally_scale("fcv_[1-7]$", "fcv") %>%
  tally_scale("sds_", "sds") %>%

  tally_scale("panas_pos_[0-9]{1,2}$", "panas_pos") %>%
  tally_scale("panas_neg_[0-9]{1,2}$", "panas_neg") %>%

  tally_scale("rrs_brood_[0-9]$", "rrs_brood") %>%
  
  tally_scale("ace_[0-9]$", "ace") %>% 
  
  # -- data types -- #
  mutate_at(vars(one_of(columns_to_numeric)), as.numeric) %>% 
  # -- re-order factors -- #
  mutate(income = factor(income, levels = c(
    "Less than $10,000",
    "$10,000 to $19,999",
    "$20,000 to $29,999",
    "$30,000 to $39,999",
    "$40,000 to $49,999",
    "$50,000 to $59,999",
    "$60,000 to $69,999",
    "$70,000 to $79,999",
    "$80,000 to $89,999",
    "$90,000 to $99,999",
    "$100,000 to $149,999",
    "$150,000 to $199,999",
    "$200,000 to $249,999",
    "$250,000 to $299,999",
    "$300,000 or more"
  )))  %>%
  
  mutate(nature_freq_factor = as.factor(as.character(nature_freq))) %>% 
  mutate(nature_freq_factor = forcats::fct_recode(nature_freq_factor,
                                                  "Never" = "1",
                                                  "Once a year" = "2",
                                                  "Once every three months" = "3",
                                                  "Once a month" = "4",
                                                  "2-3 times a month" = "5",
                                                  "Once a week" = "6",
                                                  "2-3 days a week" = "7",
                                                  "3-5 days a week" = "8",
                                                  "6-7 days a week" = "9")
         ) %>%
  
  # -- discretizing continuous variables for visualizations -- #
  mutate(high_ace = case_when(
    ace <= 4 ~ 0, 
    ace > 4 ~ 1)) %>% 
  mutate(high_macarthur_us_rung = case_when(
    macarthur_us_rung <= median(macarthur_us_rung) ~ 0,
    macarthur_us_rung > median(macarthur_us_rung) ~ 1)) %>% 
  cbind(get_race(.$race))
```



```{r, echo=FALSE}
# ------ End Preprocessing ------ #
# ----- Run all chunks above -----#
```

# 
```{r}
# filepath_output <- "data/proc/national_study_2b_proc.csv"
df_proc %>% 
  write_csv(here(params$outputfile))
```

# Session Info
```{r, message=F}
sessionInfo()
```

