---
title: "National Qualtrics Study"
author: "Ashish"
date: "4/26/2021"
output: html_document
---

# Initialization
```{r}
rm(list=ls())
library(here)
library(tidyverse)
library(tidylog)
theme_set(theme_bw())


```

# Preprocessing
## Functions
```{r}
codebook_renamer <- function(df, codebook, old_col_name="old_col_name", new_col_name="new_col_name"){
  codebook <- codebook %>%
    dplyr::filter(.data[[old_col_name]] %in% names(df))
  df %>% 
  rename_at(vars(codebook[[old_col_name]]), ~codebook[[new_col_name]])
}
recoder <- function(column, var_regex, var_col_name, codebook=codebook_values){
  codebook <- codebook %>%
    dplyr::filter(!is.na(old_value) | !is.na(new_value)) %>% 
    dplyr::mutate_at(vars(old_value, new_value), ~replace_na(., "<na_value>"))
  column <- column %>% 
    replace_na(., "<na_value>")
	level_key <- codebook %>%
	  dplyr::filter(.data[[var_col_name]]==!!var_regex) %>% 
	  dplyr::mutate(old_value = tolower(old_value)) %>% 
		dplyr::select(old_value, new_value) %>%
		deframe
	level_key <- c(level_key, "<na_value>"=NA)
	recoded_column <- recode(tolower(column), !!!level_key)
	recoded_column <- as.numeric(recoded_column)
	 return(recoded_column)
}
codebook_recoder <- function(df, codebook, var_col_name="var_regex"){
  var_regexes <- unique(codebook[[var_col_name]])
  for(var in var_regexes){
    df <- df %>% 
      dplyr::mutate_at(vars(matches(paste0("^", var))), 
                       ~recoder(., var_regex=var, var_col_name=var_col_name))
  }
  return(df)
}
tally_scale <- function(df, scale_regex, new_col_name=NULL, pid_col="pid", join_function=dplyr::full_join, na.rm=T, tally_function=mean){
  # Be careful when aggregating multiple subscales from same scale, might need to use negative lookbehinds e.g. (?<!mean)$
  # TODO: implement this to accept named vector and eventually codebook
  if(is.null(new_col_name)) new_col_name <- scale_regex # if user did not supply a new column name, use the scale_regex
  scale_regex <- paste0("^", scale_regex) # append ^ to start of regex
  cols_to_tally <- names(df)[str_detect(names(df), scale_regex)] # identify columns to aggregate
  print(paste0("[",new_col_name, "] tallying columns:"))
  print(cols_to_tally)
  df_tally <- df %>% 
    dplyr::select(one_of(pid_col), one_of(cols_to_tally)) %>% # select columns to aggregate
    tidyr::pivot_longer(-one_of(pid_col)) %>% # convert to long format 
    dplyr::group_by_at(pid_col) %>% # group by participant
    dplyr::mutate(value = as.numeric(value)) %>% # change values to numeric
    dplyr::summarize(!!new_col_name := tally_function(value, na.rm=na.rm)) # aggregate according to tally_function
  if(!is.null(join_function)){
    df_tally <- df %>%
      join_function(df_tally) # join aggregated scores with original dataframe using join_function
  }
  return(df_tally)
}

```

## Read data
```{r}
codebook_filepath <- here("lib/Winter_2020_Survey_EWB_S2B_National_April_26_2021_11_30_codebook.xlsx")
codebook_vars <- readxl::read_excel(codebook_filepath, sheet="variables")
codebook_values <- readxl::read_excel(codebook_filepath, sheet="values")

df_file <- read_csv(here("data/raw/Winter 2020 Survey EWB - S2B (National)_April 29, 2021_16.30.csv"))
df_raw <- df_file %>% 
  slice(-1:-2) %>% 
  # -- rename columns -- #
  codebook_renamer(codebook=codebook_vars)



```

## Process data
```{r}
df_recoded <- df_raw %>%
	# -- recode variables -- #
	codebook_recoder(codebook=codebook_values)

df_recoded %>% write_csv("processed_Winter_2020_Survey_EWB_S2B_National.csv")

df_proc <- df_recoded %>%
  # -- remove failed attention checks -- #
  # filter(ac_1 == 1 & ac_2 == 1 & ac_3 == 1 & ac_4 == 1) %>%
  filter(gc == 1) # gc == 1 is qualtrics way of marking good participants
```

# END PREPROCESSING
```{r}
# ------ End Preprocessing ------ #
# ----- Run all chunks above -----#
```


# Attention checks
```{r}
# How many participants passed attention check 1
df_recoded %>% 
  pull(ac_1) %>% 
  table(useNA="always")
# How many participants passed attention check 2
df_recoded %>% 
  pull(ac_2) %>% 
  table(useNA="always")
# How many participants passed attention check 3
df_recoded %>% 
  pull(ac_3) %>% 
  table(useNA="always")
# How many participants passed attention check 4
df_recoded %>% 
  pull(ac_4) %>% 
  table(useNA="always")

# failed >= 1 ac and gc == 1
# i.e. participants who qualtrics mistakenly marked as good
df_recoded %>% 
  filter((ac_1 != 1 | 
            ac_2 != 1 |
            ac_3 != 1 |
            ac_4 != 1) &
           gc == 1) %>% 
  nrow
# df_recoded %>% 
#   filter((ac_1 != 1 | 
#             ac_2 != 1 |
#             ac_3 != 1 |
#             ac_4 != 1) &
#            gc == 1) %>% 
#   write_csv("src/output/rejections_Winter_2020_Survey_EWB_S2B_National_April_26_2021_11_30.csv")

# passed all AC and gc == 1
df_recoded %>% 
  filter((ac_1 == 1 &
            ac_2 == 1 &
            ac_3 == 1 &
            ac_4 == 1) &
           gc == 1) %>% 
  nrow

df_recoded %>% 
  filter(gc == 1) %>% 
  nrow
```

## How many participants passed each attention check?
```{r}
df_proc %>% 
  select(starts_with("ac_")) %>% 
  rowwise() %>% 
  summarize(ac_passes = sum(c(ac_1, ac_2, ac_3, ac_4))) %>% 
  pull(ac_passes) %>% 
  table
```

# Quotas
```{r}
df_proc %>% 
  group_by(gender) %>% 
  summarize(n = n())
df_proc %>% 
  group_by(race) %>% 
  summarize(n = n())
  

```




# Session Info
```{r}
sessionInfo()
```

